name: Github Action No. 2


on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v3
      - name: action/setup-node@v3
        with:
        node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build    